Salesforce/Salesforce Fundamental/src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Max_Size__c</fullName>
        <defaultValue>60</defaultValue>
        <label>Max Size</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>My_Count__c</fullName>
        <label>My Count</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_Of_Students__c</fullName>
        <label>Number Of Students</label>
        <summaryForeignKey>Student__c.Class__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/Salesforce Fundamental/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/Salesforce Triggers/src/classes/StudentTriggerApex.cls
/** 
* Author: Dheeraj Kumar
* Created Date: 21/01/2016
* Name:  ClassTriggerApex
* Desc: Student__c trigger apex helper class 
*/
public class StudentTriggerApex {
    
    public static List<Student__c> newList = new List<Student__c>();
    public static List<Student__c> oldList = new List<Student__c>();
    public static Map<Id,Student__c> newMap = new Map<Id,Student__c>();
    public static Map<Id,Student__c> oldMap = new Map<Id,Student__c>();     
    
    /**
*    @param List<Contact>
*    @return void 
*    @desc add error when class has not seats available 
*/
    public static void notAllowInsertStudent() {
        for(Student__c std : newList )
        {
            Class__c stdClass = [SELECT Max_Size__c,Number_Of_Students__c FROM Class__c WHERE Id=:std.Class__c];
            if(stdClass.Max_Size__c <= stdClass.Number_Of_Students__c)
            {
                std.addError('No more seat in selected class');
            }
        }
        
    }
    
    
      
/**
*    @param void
*    @return void 
*    @desc updating mycount field in class object
*/
    public static void updateMyCount() {
        
        if(oldList.size() == 0) {
            for(Student__c st : newList) {
                Class__c cls =  [SELECT Id,My_Count__c FROM Class__c WHERE Id =:st.Class__c ] ;
                cls.My_Count__c ++;
                
            }
        }
        else if(newList.size() == 0 ) {
            for(Student__c st : oldList) {
                Class__c cls =  [SELECT Id,My_Count__c FROM Class__c WHERE Id =:st.Class__c ] ;
                cls.My_Count__c --;
            }
            
        }
        else {
            
            
            
            
            
        }
        
    }
    
}