Salesforce/Salesforce Fundamental/src/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/Salesforce Fundamental/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/Salesforce Apex Assignment/src/classes/ClassStudentsMap.cls
/*Question 2 Map of class id is a key and value is a set of students*/
public class ClassStudentsMap {
    // method return map of class id of key and set of students in that class of values 
    public static Map<ID, Set<Student__c>> getAllClassByStudent() {
		
      	List<Class__c> classes=[Select Id,(select Name from Students__r) from Class__c];
		Map<Id,Set<Student__c>> mapName=new Map<Id,Set<Student__c>>();
		for (Class__c class1 : classes) {
    			mapName.put(class1.id, new Set<Student__c>(class1.Students__r));
        }
      
        return mapName;
    }

}