Salesforce/Salesforce Fundamental/src/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce/assignment1/src/objects/Class__c.object
    <fields>
        <fullName>MyCount__c</fullName>
        <label>MyCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

Salesforce/Salesforce Fundamental/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SalesForce/Assignment_1/src/objects/Student__c.object
    <fields>
        <fullName>MyCount__c</fullName>
        <label>MyCount</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

Salesforce/TriggerAssignment/src/classes/UpdateMyCountTriggerHelper.cls
public class UpdateMyCountTriggerHelper {
    
    public static List<Class__c> newList = new List<Class__c>();

    
    
    
    
 // Public Static List<Student__c> oldList = null;
  public static List<Class__c> clsList = [SELECT Id,MyCount__c FROM Class__c];
   public Static void insertMyCount(List<Student__c> oldList)
   {
       oldList=Trigger.new;
       for(Student__c stdNew :oldList)
        {
            for(class__c cls : clsList)
            {
                if(cls.Id==stdNew.Class__c){
                    cls.MyCount__c += 1;
                }
            }
        }
   }

}