SalesForce/ValidationRuleSOQLWorkFlow/src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Board__c</fullName>
        <label>Board</label>
        <picklist>
            <picklistValues>
                <fullName>RAJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CBSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIHAR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <label>Fee</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SalesForce/VF/VF/src/classes/ClassController.cls
public with sharing class ClassController {
    
    public Class__c recordsToDisplay { get; private set; }
    public Class__c saveRecords { get; private set; }
    public String idToUpdate {get;set;}
    public boolean displayPopup {get; set;} 
    
    public String thisClass {get; set;}
    String query = 'SELECT Id, Name, fee__c, board__c FROM Class__c ';
    public ClassController(ApexPages.StandardController controller) {
    }
    
    public void saveDetails() {  
        displayPopup = false;
        update saveRecords;
        
    }  
    
    public void deleteDetails() { 
        saveRecords = [SELECT id,Name,fee__C FROM Class__c WHERE id = :idToUpdate];
        delete saveRecords;
    }  
   
    public void ShowDataToEdit() { 
        saveRecords = [SELECT id, Name, fee__c,board__C FROM Class__c WHERE id = :idToUpdate];
        displayPopup = true;    
    }   
    
    public List<Class__C> getRecords() 
    {
        return Database.query(query);
    }  
}