SalesForce Assignment/SOQL Assignment/src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>MaxCount__c</fullName>
        <label>MaxSize</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MyCount__c</fullName>
        <label>MyCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Class</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SalesForce Assignment/SOQL Assignment/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Subjects__c</fullName>
        <label>Subjects</label>
        <picklist>
            <picklistValues>
                <fullName>Hindi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maths</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Science</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SalesForce Assignment/SOQL Assignment/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sex__c</fullName>
        <label>Sex</label>
        <picklist>
            <picklistValues>
                <fullName>MALE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FEMALE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SalesForce/Assignment_1/src/objects/Student__c.object
    <fields>
        <fullName>MyCount__c</fullName>
        <label>MyCount</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

SalesForce Assignment/Test Classes/src/classes/TestTriggers.cls
@isTest
public class TestTriggers {
 @isTest
 public static void  TestOpportunityWhenStageChange()
     {  
       Date Opportunitydate =Date.newInstance(2014, 07, 15);
       Opportunity newOpportunity=new Opportunity(Name='test',StageName='Qualification',CloseDate=Opportunitydate);
       insert newOpportunity;
         test.startTest(); 
       try
       {
           update newOpportunity;
       }
       catch(Exception ee)
       { 
           system.debug('error in  line'+ee.getLineNumber()+'due to'+ee.getMessage());
       }
       Test.stopTest();
     }
   @isTest  
   public static void testContactTriggerWhenInsert(){ 
      Test.startTest();
      contact newcontact=new contact(FirstName='nikhil',LastName='tinkar',Subjects__c='Hindi');
      try{
      	insert newcontact;
      }
      catch(Exception ee){ 
        system.debug('error in  line'+ee.getLineNumber()+'due to'+ee.getMessage());
      }
      Test.stopTest();
    }
    @isTest
    public static void  TestContactTriggerWhenUpdate()
       {  
           Test.startTest();
       contact newcontact=new contact(FirstName='nikhil',LastName='tinkar',Subjects__c='English');
       insert newcontact;
       newcontact.Subjects__c = 'Hindi';
        try
       {
        update newcontact;
       }
    catch(Exception ee)
       { 
        system.debug('error in  line'+ee.getLineNumber()+'due to'+ee.getMessage());
       }
     Test.stopTest();    
               
    }
    
   @isTest
   public static void  TestForNotAllowDeleteClass()
   {   
       Class__c newClass = new Class__c(Name__c = 'secondary',MaxCount__c=5,MyCount__c=0);
       insert newClass;
       System.debug(newClass);
       student__c newStudent1=new student__c(Last_Name__c='rakesh',Class__c=newClass.id,Sex__c='Female'); 
       student__c newStudent2=new student__c(Last_Name__c='ravi',Class__c=newClass.id,Sex__c='Female'); 
       insert newStudent1;
       insert newStudent2;
       System.debug('student1'+newStudent1+'student2'+newStudent2);
       Test.startTest();
       try
       {
           delete newClass;
       }
       catch(Exception ee)
       { 
           system.debug('error in  line'+ee.getLineNumber()+'due to'+ee.getMessage());
       }
       Test.stopTest();
   }
   
    @isTest
     public static void TestStudentTrigger(){ 
     Id classId = 'a0628000004Doc3';
    student__c newStudent=new student__c(Last_Name__C='test',Class__c=classId);
    Test.startTest();
    try
    {
        insert newStudent;
    }
    catch(Exception ee)
    { 
        system.debug('error in  line'+ee.getLineNumber()+'due to'+ee.getMessage());
    }
     Test.stopTest();
   }
    
}