SalesForce Assignment/Apex Assignment/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BillToContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SalesForce Assignment/Apex Assignment/src/classes/AccountUpdate.cls
public class AccountUpdate {
public static void updateManagerField(List<Opportunity> opportunityList) {
    List<Opportunity> listToUpdate = new List<Opportunity>();
       for(Opportunity opp : opportunityList) {
           if(opp.BillToContact__c != null && opp.Manager__c == null) {
               opp.Manager__c=opp.BillToContact__r.Account.id;
                listToUpdate.add(opp);
           }
       }
      update listToUpdate;

                    
   }
}