SalesForce Assignment/Apex Assignment/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BillToContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/TriggerAssignment/src/classes/OpportunityController.cls
public class OpportunityController {
    public static void populateInOpportunity(List<Opportunity> oppList) {
        for(Opportunity opportunity:oppList){
            if(opportunity.BillToContact__c != null && opportunity.Manager__c == null) {
                // opportunity.Manager__c = opportunity.BillToContact__c ->  AccountId;
                // Map contact Id to Account Id
                // After this loop for new list and assign account id
            }
        }
    }
}