SalesForce Assignment/Apex Assignment/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BillToContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/Salesforce Apex Assignment/src/classes/RelatedAccounts.cls
/*Question 8 : populate Manager Field by related account*/
public class RelatedAccounts {
    
    public static void  updateManagerField(List<Opportunity> oppList) {
 			for(SObject opp:oppList){
            if(opp instanceof Opportunity) {
                Opportunity opportunity=(Opportunity)opp;
                if(opportunity.BillToContact__c != null && opportunity.Manager__c == null)
                {
                    opportunity.Manager__c =opportunity.AccountId;
                }
            }
            
        }
     
    }
  	}