salesforce/VisualForceAssignment2/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Computers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shoes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sports</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

SalesForce/VF2/src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Custom Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce/VisualForceAssignment2/src/objects/PurchaseOrder__c.object
<CustomObject>
    <label>PurchaseOrder</label>
    <nameField>
        <label>PurchaseOrder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PurchaseOrders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce/VisualForceAssignment2/src/objects/PurchaseOrderLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProductCode__c</fullName>
        <label>ProductCode</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>PurchaseOrderLineItems</relationshipLabel>
        <relationshipName>PurchaseOrderLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PurchaseOrder__c</fullName>
        <label>PurchaseOrder</label>
        <referenceTo>PurchaseOrder__c</referenceTo>
        <relationshipLabel>PurchaseOrderLineItems</relationshipLabel>
        <relationshipName>PurchaseOrderLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Quantity</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <formula>if(AND(Quantity__c &lt;&gt; null,Price__c &lt;&gt; null),0,Quantity__c  * Price__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TotalPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>PurchaseOrderLineItem</label>
    <nameField>
        <label>PurchaseOrderLineItems Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PurchaseOrderLineItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce/VisualForceAssignment2/src/classes/ShoppingController.cls
public class ShoppingController {
    
    public  List <product2> products { get; set; }
    
    public  ID orderId {get;set;}
    
    public String idOfProductToAdd {get;set;}
  
    public String SelectedCategoty { get; set; }
    
    public List<PurchaseOrderLineItem__c> items {
        get
          {
            List<PurchaseOrderLineItem__c> item = [select ID,ProductCode__c,Name,Price__c,Quantity__c,TotalPrice__c from PurchaseOrderLineItem__c where PurchaseOrder__c =: orderId];
            return item;
          }
    set;}
   
    public List<SelectOption> Category
    {
        get
        {
         List<SelectOption> options = new List<SelectOption>();
         Schema.DescribeFieldResult fieldResult = product2.category__c .getDescribe();
         List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
         
         for( Schema.PicklistEntry f : ple)
             options.add(new SelectOption(f.getLabel(), f.getValue()));
         
        return options;
        }
    }
  
      public ShoppingController(ApexPages.StandardController controller)
       { 
        orderId = System.currentPageReference().getParameters().get('id');
       }
    
      public  void calcPricing()
       {
        products = [select ID,ProductCode,Name,Price__c,category__c from product2 where category__c =:SelectedCategoty];
        system.debug(products);
       }
      
      public void RemoveFromCart()
       {
         List <PurchaseOrderLineItem__c> product = [select ID,name from PurchaseOrderLineItem__c where ID =:idOfProductToAdd Limit 1];
         PurchaseOrderLineItem__c getProduct;
         if(product.size()>0)
           {
            getProduct=product.get(0);
           }
        delete getProduct;
       }
    
      public void AddToCart()
       { 
        List<PurchaseOrderLineItem__c> ListItems; 
        
        List <product2> product=[select ID,ProductCode,Name,Price__c,category__c from product2 where ID =:idOfProductToAdd Limit 1];
       
        Product2 getProduct;
        PurchaseOrderLineItem__c PurchaseOrder;
    
        if(product.size()>0)
          {
           getProduct=product.get(0);
          }
        ListItems = [select ID,name,Quantity__c,Price__c,TotalPrice__c from PurchaseOrderLineItem__c where Product__r.id =:getProduct.id and purchaseOrder__c =:orderId Limit 1];
  
        if(ListItems.size()>0)
         {				
          PurchaseOrder=ListItems.get(0);
          PurchaseOrder.Quantity__c+=1;
          update PurchaseOrder;
         }    
       else
        {
         PurchaseOrder =new PurchaseOrderLineItem__c(name=getProduct.name,price__c=getProduct.Price__c,ProductCode__c=getproduct.ProductCode,Product__c=getProduct.id,PurchaseOrder__c = orderId);
         insert PurchaseOrder;
        }
    }
    
}