salesforce/assignment1/src/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce/assignment1/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce/JavascriptAssignment/src/classes/DeleteStudentController.cls
public class DeleteStudentController {
 public  List<Student__c> selectedsts{get;set;}
   private ApexPages.StandardSetController standardController;

   public DeleteStudentController(ApexPages.StandardSetController standardController)
   {
       this.standardController = standardController;
   }

   public void bumpCases()
   {       
       // Get the selected records (optional, you can use getSelected to obtain ID's and do your own SOQL)
       selectedsts = (List<Student__c>) standardController.getSelected();
       selectedsts =[select name,id,class__r.Name from student__c where id In : selectedsts];
             
   }
   public PageReference deleteStudent() {
       delete selectedsts ;
       System.debug('executed');
       return standardController.cancel();
   }

  
}