salesforce/assignment1/src/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce/assignment1/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>LastName</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce/TestClasses/src/classes/TestNotAllowInsertStudent.cls
@isTest
public class TestNotAllowInsertStudent {
   public static testMethod void  TestStudentTrigger()
    { 
      Id classId = 'a0628000004Doc3';
     student__c newStudent=new student__c(LastName__C='test',Class__c=classId);
     Test.startTest();
     try
     {
         insert newStudent;
     }
     catch(Exception ee)
     { 
         system.debug('error in  line'+ee.getLineNumber()+'due to'+ee.getMessage());
     }
      Test.stopTest();
     
    }
}