salesforce/assignment1/src/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce/assignment1/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <formula>FLOOR((TODAY() - DOB__c ) / 365)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce/WebServicesAssignment/src/classes/SiteHomeController.cls
public with sharing class SiteHomeController {
   public List<Student__c> stdList{set ;get ;} 
   public Student__c student{set ;get ;}
   public String selectedValue{set ;get ;}
   public boolean showDetail{set ;get ;}
   public ApexPages.StandardController controller;
   public SiteHomeController(ApexPages.StandardController con) {
showDetail = false;
       student = new Student__c();
   }
   
   public List<SelectOption> getselectList() {
       System.debug('hii');
       List<SelectOption> selectList = new List<SelectOption>();
       stdList = [select Name from Student__c];
       for(Student__c std : stdList) {
           selectList.add(new SelectOption(std.Id,std.Name));
       }
       return selectList;
   }
   
   public PageReference getStudent() {
       try{
           showDetail = true;
           student = [select Id,Name,Age__c,Class__c,DOB__c from Student__c where id =:selectedValue limit 1] ;
       	return null ;
       }
       catch(Exception e){
           return new PageReference('/apex/errorfinder');
       }
   }
 }