salesforce/assignment1/src/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce/assignment1/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

JavaScript/src/classes/DeleteStudentsController.cls
public class DeleteStudentsController {
    public List<Student__c> studentList {set ; get;}
    public string callfunc{get;set;}
    Set<ID> idSet{set;get;}
    public DeleteStudentsController(ApexPages.StandardSetController controller) {
        if(idSet == null) {
            idSet = new Set<Id>();
        }
        List<Student__c> stdList = controller.getSelected();
        for(Student__c std : stdList) {
            idSet.add(std.ID);
        }
        studentList = [select ID,Name,Class__C from Student__c where ID IN : idSet];
    }
    public void deleteAll() {
        Database.delete(studentList);
    }
}