salesforce/assignment1/src/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce/assignment1/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestClass/src/classes/TestClassWithStudentId.cls
@isTest
public class TestClassWithStudentId {
    public static testMethod void testgetClassWithStudentId(){
        Map<Id,List<Student__c>> classMap = new Map<Id,List<Student__c>>();
        List<Class__c> clsList = new List<Class__c>();
        Set<Id> idSet = new Set<Id>();
        for(Class__c classObject : [select id from Class__c]) {
            idSet.add(classObject.Id);
        }
        clsList = [select id,(Select id from Class_Student__r) from Class__c where id in:idSet];
        for(Class__c cls : clsList) {
            classMap.put(cls.Id, cls.Class_Student__r);
        }
        System.assertEquals(classMap, ClassWithStudentId.getClassWithStudentId());
    }
}