salesforce/assignment1/src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>MaxSize__c</fullName>
        <label>MaxSize</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MyCount__c</fullName>
        <label>MyCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce/assignment1/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>LastName</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sex__c</fullName>
        <label>Sex</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SalesForce/Assignment_1/src/objects/Student__c.object
    <fields>
        <fullName>MaxSize__c</fullName>
        <label>MaxSize</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

SalesForce/Assignment_1/src/objects/Student__c.object
    <fields>
        <fullName>MyCount__c</fullName>
        <label>MyCount</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

salesforce/TestClasses/src/classes/TestForNotAllowDeleteClassTrigger.cls
@isTest
public class TestForNotAllowDeleteClassTrigger {
    public static testMethod void  TestForNotAllowDeleteClass()
    {   
        class__c newClass = new class__c(name = 'secondary',MaxSize__c=5,MyCount__c=0);
        insert newClass;
        System.debug(newClass);
        student__c newStudent1=new student__c(LastName__C='rakesh',Class__c=newClass.id,Sex__c='Female'); 
        student__c newStudent2=new student__c(LastName__C='ravi',Class__c=newClass.id,Sex__c='Female'); 
        insert newStudent1;
        insert newStudent2;
        System.debug('student1'+newStudent1+'student2'+newStudent2);
        Test.startTest();
        try
        {
            delete newClass;
        }
        catch(Exception ee)
        { 
            system.debug('error in  line'+ee.getLineNumber()+'due to'+ee.getMessage());
        }
        Test.stopTest();
        
        
        
    }
}