salesforce/assignment1/src/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce/assignment1/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>LastName</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce/WebServicesAssignment/src/classes/CreateStudent.cls
global class CreateStudent {
   webservice static String CreateStudentWithRequiredField(String firstName,String lastName,String className) {
       Class__c newClass = new Class__c(name=className);
       insert newClass;
       student__c newStudent =new student__c(First_Name__c=firstName,LastName__c=lastName,Class__c=newclass.id);
       insert newStudent;
       return newStudent.id;
    }
     webservice static String CreateStudentWithClassid(String firstName,String lastName,String ClassId) {
       student__c newStudent =new student__c(First_Name__c=firstName,LastName__c=lastName,Class__c=ClassId);
       insert newStudent;
       return newStudent.id;
    }
}