salesforce/assignment1/src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Board__c</fullName>
        <label>Board</label>
        <picklist>
            <picklistValues>
                <fullName>RAJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CBSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIHAR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RAJ_CBSE_BIHAR__c</fullName>
        <label>Fee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce/VisualForcesAssignment1/src/classes/ManageClassController.cls
public with sharing class ManageClassController {
   
   // To Display the Records
   public Class__c recordsToDisplay { get; private set; }
   // To save the Records
   public Class__c saveRecords { get; private set; }
   // To Update the Record
   public String idToUpdate {get;set;}
   // To display the Popup
   public boolean displayPopup {get; set;} 
   
   public String thisClass {get; set;}
   // Query to get the Details
   String query = 'SELECT Id, Name__c, RAJ_CBSE_BIHAR__c, board__c FROM Class__c ';
   // Constructor
   public ManageClassController(ApexPages.StandardController controller) {
   }
   /*
    * Name:saveDetails
    * Description: Save the Class afterEdit
    */
   public void saveDetails() {  
       displayPopup = false;
       update saveRecords;
       
   }  
   /*
    * Name:deleteDetails
    * Description: Delete the Details 
    */
   public void deleteDetails() { 
       saveRecords = [SELECT 
                      id,name__c,RAJ_CBSE_BIHAR__c 
                      FROM
                      Class__c 
                      WHERE id = :idToUpdate];
       delete saveRecords;
   }  
   /*
    * Name:ShowDataToEdit
    * Description: Displays the Data to Edit
    */
   public void ShowDataToEdit() { 
       // Query to fetch the Records
       saveRecords = [SELECT
                      id, name__c, RAJ_CBSE_BIHAR__c,board__C 
                      FROM Class__c
                      WHERE id = :idToUpdate];
       displayPopup = true;    
   }   
   /*
    * Name:getRecords
    * Description: Fetches the Data 
    */ 
   public List<Class__C> getRecords() 
   {
       return Database.query(query);
   }  
}